# 관리자 권한 갖기
sudo: required
# 언어 선택
language: generic
# 도커 환경 구성
services:
  - docker
#스크립트를 실행할 수 있는 환경 구성
# before_install:
#   - echo "start creating an image with dockerfile"
#   - docker build -t hsj1202/docker-react-app -f Dockerfile.dev .
# # 실행할 스크립트
# script: -docker run -e CI=true hsj1202/docker-react-app npm run test -- --coverage
# 테스트 성공 후 할 일

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Docker-React-App-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-022794725494"
  bucket_path: "docker-react-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
